export const Names = {


history_books_name : [
    "Time's Tapestry",
    "Ancient Echoes",
    "Rise & Fall",
    "Lost Civilizations",
    "War Chronicles",
    "Cultural Odyssey",
    "Threads of Time",
    "Tech Evolution",
    "Written Worlds",
    "Women in History",
    "Turning Points",
    "Empire Lessons",
    "Hidden Stories",
    "Mapping History",
    "Global Threads",
    "Renaissance",
    "Triumphs & Tragedies",
    "Shaping Minds",
    "Nation Revolutions",
    "Cross-Cultural History"
],

fantasy_books_name:[
    "Realm's End",
    "Sorcerer's Quest",
    "Dragon's Dawn",
    "Enchanted Echoes",
    "Shadowbane",
    "Feywild Chronicles",
    "Crystal Spell",
    "Epic Enchantment",
    "Cursed Kingdoms",
    "Throne of Legends",
    "Mystic Masquerade",
    "Eternal Frost",
    "Witchwood Secrets",
    "Starborn Prophecy",
    "Moonlit Mage",
    "Tales of Arcane",
    "Fablestone",
    "Skyward Odyssey",
    "Crimson Crown",
    "Whispering Woods"
],

romance_books_name:[
    "Eternal Hearts",
    "Whispers of Love",
    "Moonlit Promises",
    "Enchanted Embrace",
    "Passion's Prelude",
    "Stolen Kisses",
    "Fates Intertwined",
    "Roses and Romance",
    "Love Beyond Time",
    "Star-Crossed Desire",
    "Secrets of the Heart",
    "Sunset Serenade",
    "Tangled Affections",
    "Boundless Devotion",
    "Summer Love Story",
    "Unwritten Letters",
    "Heartstrings Harmony",
    "Inamorata",
    "Twilight Reverie",
    "Captivating Connections"
],

scifi_books_name: [
    "Galactic Nexus",
    "Chronicles of Tomorrow",
    "Quantum Paradox",
    "Starship Odyssey",
    "Neural Frontier",
    "Astral Echoes",
    "Cosmic Alchemy",
    "Beyond Infinity",
    "Nanotech Chronicles",
    "Temporal Rift",
    "Synthetic Dreams",
    "Astrogenesis",
    "Metaverse Chronicles",
    "Infinite Horizons",
    "Cybernetic Legacy",
    "Beyond the Veil",
    "Singularity's Embrace",
    "Exoplanet Enigma",
    "Orbital Resonance",
    "Echoes of Tomorrow"
],  
advanture_books_name:[
    "Quest for the Lost City",
    "Rogue Expeditions",
    "Chronicles of Adventure",
    "Journey to the Unknown",
    "Secrets of the Wilderness",
    "Trailblazers' Tales",
    "Crimson Horizon",
    "Treasure Seekers",
    "Voyage of Legends",
    "Whispers of the Jungle",
    "Echoes from the Abyss",
    "Serpent's Trail",
    "Mysteries Beyond the Map",
    "Island of Enigmas",
    "Destiny's Compass",
    "Edge of Eternity",
    "Legacy of the Nomad",
    "Windswept Odyssey",
    "Adventures in the Ether",
    "Chasing the Horizon"
],
selfdev_books_name:[
    "Path to Empowerment",
    "Awakening Your Potential",
    "The Inner Journey",
    "Becoming Your Best Self",
    "Unleash Your Brilliance",
    "Mastery of Mindset",
    "Elevate Your Existence",
    "Finding Your North Star",
    "The Art of Self-Growth",
    "Transformative Insights",
    "Embrace Your Destiny",
    "Radiant Resilience",
    "The Power Within You",
    "Unlocking Greatness",
    "Embarking on Excellence",
    "Redefining Possibilities",
    "Blueprint for Fulfillment",
    "Thriving from Within",
    "Evolution of You",
    "Charting a Life of Purpose"
],

}